import { Typography, Colors, BorderRadiuses } from 'react-native-ui-lib';

BorderRadiuses.loadBorders({
  br8: 8,
  br10: 10,
  br12: 12,
  br16: 16,
  br20: 20,
  br50: 16,
});

Colors.loadColors({
  white: '#fff',
  grey10: '#F7F8F9',
  grey20: 'rgba(0, 21, 47, 0.03)',
  grey30: 'rgba(0, 21, 47, 0.06)',
  grey40: '#D5D6D8',
  grey50: 'rgba(24, 24, 24, 0.22)',
  grey60: '#BFC1C4',
  grey70: '#A8AFB7',
  grey80: '#7D8287',
  grey90: '#333333',
  grey100: '#181818',
  grey110: '#121212',
  yellow10: '#fff7ee',
  red10: '#fff2f2',
  red70: '#ff4b4b',
  accent: '#9C73F8FF',
  //
  link: '#7C2EFEFF',
  error: '#F71D1D',
  success: '#26CA4E',
  warning: '#FDB818',
});

export const initUiTheme = () => {
  Typography.loadTypographies({
    h1: {
      paddingTop: 1,
      top: 1,
      fontSize: 24,
      fontWeight: '500',
      lineHeight: 24,
      color: Colors.grey100,
      fontFamily: 'HelveticaNeueBold',
    },
    h2: {
      fontSize: 20,
      fontWeight: '500',
      lineHeight: 24,
      color: Colors.grey100,
      fontFamily: 'HelveticaNeueBold',
    },
    h3: {
      fontSize: 16,
      fontWeight: '500',
      lineHeight: 22,
      color: Colors.grey100,
      fontFamily: 'HelveticaNeueBold',
    },
    bodyB1: {
      fontSize: 18,
      fontWeight: '700',
      lineHeight: 25,
      color: Colors.grey100,
      fontFamily: 'HelveticaNeueBold',
    },
    bodyR1: {
      fontSize: 18,
      fontWeight: '400',
      lineHeight: 25,
      color: Colors.grey100,
      fontFamily: 'HelveticaNeue',
    },
    bodyB2: {
      fontSize: 16,
      fontWeight: '700',
      lineHeight: 22,
      color: Colors.grey100,
      fontFamily: 'HelveticaNeueBold',
    },
    bodyM2: {
      fontSize: 16,
      fontWeight: '500',
      lineHeight: 22,
      color: Colors.grey100,
      fontFamily: 'HelveticaNeueMedium',
    },
    bodyR2: {
      fontSize: 16,
      fontWeight: '400',
      lineHeight: 22,
      color: Colors.grey100,
      fontFamily: 'HelveticaNeue',
    },
    bodyI2: {
      fontSize: 16,
      fontWeight: '400',
      lineHeight: 22,
      color: Colors.grey100,
      fontFamily: 'HelveticaNeueItalic',
    },
    bodyB3: {
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 20,
      color: Colors.grey100,
      fontFamily: 'HelveticaNeueBold',
    },
    bodyR3: {
      fontSize: 14,
      fontWeight: '400',
      lineHeight: 20,
      color: Colors.grey100,
      fontFamily: 'HelveticaNeue',
    },
    bodyM3: {
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 20,
      color: Colors.grey100,
      fontFamily: 'HelveticaNeueMedium',
    },
    bodyM4: {
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 17,
      color: Colors.grey100,
      fontFamily: 'HelveticaNeueMedium',
    },
    bodyR4: {
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 17,
      color: Colors.grey100,
      fontFamily: 'HelveticaNeue',
    },
    bold: { fontFamily: 'HelveticaNeueBold' },
    italic: { fontFamily: 'HelveticaNeueItalic' },
    boldItalic: { fontFamily: 'HelveticaNeueBoldItalic' },
  });
};
